# Generated by Django 3.2.12 on 2022-04-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220416_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, help_text='eg https://www.podcast.com', max_length=250),
        ),
    ]
