version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "python manage.py wait_for_db &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
#    python /podcast/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/podcast
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env.pgadmin
    ports:
      - "5050:80"

  redis:
    image: redis:alpine
    container_name: redis

  # Celery
  celery:
    restart: always
    build:
      context: .
    command: celery -A config worker -l info
    volumes:
      - .:/podcast
    container_name: celery
    depends_on:
      - db
      - redis
      - web
    env_file:
      - .env.prod

  celery_beat_scheduler:
    restart: always
    build:
      context: .
    command: celery -A config beat -l info
    volumes:
      - .:/podcast
    depends_on:
      - db
      - redis
      - celery
      - web
    env_file:
      - .env.prod


volumes:
  postgres_data: