# Generated by Django 4.0 on 2022-02-05 19:38

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import podcasts.models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_watched_episode_duration_episode_watchers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode',
            field=models.FileField(error_messages={'invalid': 'your file format is unsupported'}, help_text='it should be a mp3 file', upload_to=podcasts.models.episode_path, validators=[django.core.validators.FileExtensionValidator(['mp3'])], verbose_name='Episode Audio'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, upload_to=podcasts.models.episode_image_path, verbose_name='episode image'),
        ),
    ]
