# Generated by Django 4.0 on 2022-02-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_alter_episode_description_alter_episode_episode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='kind',
            field=models.CharField(blank=True, choices=[('full', 'full'), ('bonus', 'bonus'), ('trailer', 'trailer')], help_text='full, bonus, trailer', max_length=7, verbose_name='Episode type'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.IntegerField(blank=True, verbose_name='Episode number'),
        ),
    ]
