# Generated by Django 4.0 on 2022-02-05 21:53

import django.core.validators
from django.db import migrations, models
import podcasts.models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_alter_episode_kind_alter_episode_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode',
            field=models.FileField(blank=True, error_messages={'invalid': 'your file format is unsupported'}, help_text='it should be a mp3 file', upload_to=podcasts.models.episode_path, validators=[django.core.validators.FileExtensionValidator(['mp3'])], verbose_name='Episode Audio'),
        ),
    ]
