# Generated by Django 4.0.2 on 2022-02-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_alter_episode_duration_alter_episode_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='watched',
            name='time_watched',
            field=models.FloatField(blank=True),
        ),
    ]
