# Generated by Django 4.0.2 on 2022-02-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_alter_episode_duration_alter_watched_time_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Episode number'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.IntegerField(blank=True, null=True, verbose_name='Season number'),
        ),
    ]
