# Generated by Django 4.0.2 on 2022-02-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0012_dislike_episode_dislike_dislike_episode_dislike_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='Dislike',
            new_name='dislikes',
        ),
    ]
