# Generated by Django 4.0.2 on 2022-02-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0014_episode_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], default='d', help_text='draft, published, withdrawn', max_length=1, verbose_name='Publish Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date published'),
        ),
    ]
