# Generated by Django 4.0.2 on 2022-02-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0015_episode_status_alter_episode_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Withdrawn', 'Withdrawn')], help_text='draft, published, withdrawn', max_length=9, verbose_name='Publish Status'),
        ),
    ]
