# Generated by Django 3.2.12 on 2022-03-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0016_alter_episode_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Withdrawn', 'Withdrawn'), ('Pending', 'Pending')], help_text='draft, published, withdrawn', max_length=9, verbose_name='Publish Status'),
        ),
    ]
