# Generated by Django 3.2.12 on 2022-03-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0018_episode_current_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='current_time',
        ),
    ]
