# Generated by Django 3.2.12 on 2022-03-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0019_remove_episode_current_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listener',
            old_name='watched',
            new_name='listened',
        ),
        migrations.AddField(
            model_name='listener',
            name='streams',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
