# Generated by Django 3.2.12 on 2022-03-08 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0020_auto_20220308_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listener',
            old_name='time_watched',
            new_name='time_listened',
        ),
    ]
