# Generated by Django 3.2.12 on 2022-03-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0024_auto_20220321_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='listened',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
