# Generated by Django 3.2.12 on 2022-04-16 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0025_alter_listener_listened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='website',
            field=models.URLField(blank=True, help_text='add your website to allow your                               subscribesrs know more about you                                           eg https://www.podcast.com', validators=[django.core.validators.URLValidator()], verbose_name='webiste'),
        ),
    ]
