# Generated by Django 3.2.12 on 2022-04-16 14:45
# copied from https://github.com/jambonrose/DjangoUnleashed-1.8/blob/40667a7881/core/migrations/0001_sites_data.py

from django.conf import settings
from django.db import migrations


def add_site_data(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    new_domain = 'podcast.com'
    new_name = 'Podcast dot Com'
    site_id = getattr(settings, 'SITE_ID', 1)
    if Site.objects.exists():
        current_site = Site.objects.get(
            pk=site_id)
        current_site.domain = new_domain
        current_site.name = new_name
        current_site.save()
    else:
        current_site = Site(
            pk=site_id,  # coerce primary key
            domain=new_domain,
            name=new_name)
        current_site.save()


def remove_site_data(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    current_site = Site.objects.get(
        pk=getattr(settings, 'SITE_ID', 1))
    current_site.domain = 'example.com'
    current_site.name = 'example.com'
    current_site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_site_data,
            remove_site_data,
        ),
    ]
